# Generated by Django 4.1.1 on 2025-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_uloscharacteristic_uloscolorthread'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlosMotifImage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ulos_type', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image_data', models.BinaryField()),
                ('image_format', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Ulos Motif Image',
                'verbose_name_plural': 'Ulos Motif Images',
                'db_table': 'ulos_motif_image',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
