# Generated by Django 4.1.1 on 2025-06-24 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0009_uloscharacteristic_uloscolorthread'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlosMotifImage',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ulos_type', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image_data', models.BinaryField()),
                ('image_format', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Ulos Motif Image',
                'verbose_name_plural': 'Ulos Motif Images',
                'db_table': 'ulos_motif_image',
            },
        ),
        migrations.CreateModel(
            name='UlosColoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_id', models.CharField(max_length=20)),
                ('color_scheme_type', models.CharField(choices=[('Monochromatic', 'Monochromatic'), ('Analogous', 'Analogous'), ('Complementary', 'Complementary'), ('Complex', 'Complex'), ('Achromatic', 'Achromatic'), ('Achromatic + Accent', 'Achromatic + Accent')], max_length=20)),
                ('color_harmony_score', models.FloatField()),
                ('scheme_description', models.TextField()),
                ('hue_range', models.FloatField(default=0)),
                ('achromatic_count', models.IntegerField(default=0)),
                ('chromatic_count', models.IntegerField(default=0)),
                ('best_for', models.TextField()),
                ('ulos_application', models.TextField()),
                ('harmony_level', models.CharField(max_length=20)),
                ('primary_ratio', models.CharField(max_length=10)),
                ('secondary_ratio', models.CharField(max_length=10)),
                ('accent_ratio', models.CharField(max_length=20)),
                ('michaelson_contrast', models.FloatField()),
                ('rms_contrast', models.FloatField()),
                ('colorfulness', models.FloatField()),
                ('optimal_unique_colors', models.FloatField()),
                ('user_preference_match', models.FloatField()),
                ('colored_image_path', models.CharField(max_length=255)),
                ('used_color_codes', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ulos_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.uloscharacteristic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coloring_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ulos Coloring Result',
                'verbose_name_plural': 'Ulos Coloring Results',
                'db_table': 'ulos_coloring_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserColorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('color_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.uloscolorthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Color Preference',
                'verbose_name_plural': 'User Color Preferences',
                'db_table': 'user_color_preference',
                'unique_together': {('user', 'color_code')},
            },
        ),
    ]
